### ISSUE TITLE
Why is the `s3 sync` command so slow?

### ISSUE THREAD

**Issue by chancancode** [ember-learn/ember-api-docs-data#2]
The [bulk of the work](https://github.com/ember-learn/ember-api-docs-data/runs/1228823593?check_suite_focus=true) here is done via [s3-sync-action](https://github.com/jakejarvis/s3-sync-action), which is just a thin wrapper around the [`s3 sync` command](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html).

The sync step still takes ~5 minutes on each build, even when the files are already present on the remote S3 bucket. My expectation is that the `s3 sync` command is smart enough to diff the files in the local repo verses what is on the S3 bucket, and only upload them when they don't match. Based on a quick read of the log I can't tell if this is happening or not, and based on the amount of time it takes I am a bit suspicious.

It's not a big deal to wait a few minutes for the upload, but I want to make sure we are not incurring unnecessary S3 transfer cost (though, it's not going to be that much regardless). Someone should research this a bit (start with the [`s3 sync` docs](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html)) and see if we need to pass extra flags or something to make it do the right thing.

It's also totally possible that it's already doing what I think, just that merely the diffing and checking takes a considerable amount of time when there are so many files, which would be okay too.

If it really comes down to it, we can get a list of changed files from `git` fairly easily and limit the sync to those files, but that adds a bit of complexity and causes issues when some builds are skipped or failed, so ideally we can avoid it and just make `s3 sync` do the right thing.

**Comment by sdahlbac** [comment]
The docs say: 
> A local file will require uploading if the size of the local file is different than the size of the s3 object, the last modified time       
  of the local file is newer than the last modified time of the s3 object, or the local file does not exist under the specified 
  bucket and prefix.

there *is* a 

```
--size-only (boolean) Makes the size of each key the only criteria used to decide whether to sync from source to destination.
```

but I wonder if we'd miss uploading an actual change if we only check file sizes.

**Comment by chancancode** [comment]
Yeah, that seems like it would be too coarse.

I think what you found in the docs are good. It narrows down the problem to one of two possibilities:

1. The size of the local file is different than the size of the s3 object
2. The last modified time of the local file is newer than the last modified time of the s3 object
3. It is already doing the checks and avoided the upload, it's just that doing the checks for this many files takes time

The first seems quite unlikely/unexpected: I suppose it could happen if there is a bug in the sync action or something that causes the uploaded file to be slightly different, say, it converted the newlines between Unix and Windows conventions before uploading or something. I can believe it, but seems very unlikely.

The second (mtime differences) seems a bit more plausible. It is possible that either we didn't set the mtime correctly when initially uploading, so that they are different from what's in git, or that the mtime is set incorrectly by the checkout action (to the time when the files are checked out, i.e. when the action runs), so that they always appear newer than what is on S3.

The last one is also still quite possible, in which case there is nothing to do about it.

While I don't think `--size-only` is a good solution as we both agreed, it can somewhat help to isolate the problem between 2 and 3. If using the flag doesn't significantly bring down the run time, I think we can rule out possibility 2 (or at least conclude that it is made irrelevant by either 1 or 3). I can try to push a branch to test that later.

**Comment by chancancode** [comment]
I pushed a branch here: https://github.com/ember-learn/ember-api-docs-data/actions/runs/305222278

We'll see how it goes.

**Comment by sdahlbac** [comment]
So, it seems it is due to #2.

**Comment by chancancode** [comment]
@sdahlbac Thanks for following up! Yeah, looks like that may be the issue. To check, I pushed a new commit that does `ls -al` on some of the files to see what the mtime actually are. If you have other ideas or experiments you want to run, let me know!

**Comment by sdahlbac** [comment]
Maybe something like https://github.com/MestreLion/git-tools could help? Specifically git-restore-mtime

**Comment by chancancode** [comment]
Looks like it worked! https://github.com/ember-learn/ember-api-docs-data/runs/1279706849

@sdahlbac do you have time to clean it up and submit a pull request against the main branch? If not, I am happy to do it too.

**Comment by sdahlbac** [comment]
I can give it a go yes.

Is the fetch-depth:0 something that should be included or was that just for testing purposes?
________________________________

**Comment by chancancode** [comment]
> Is the fetch-depth:0 something that should be included or was that just for testing purposes?

I _think_ it is important – because it need to find the commit timestamp of each file, and restore the mtime to the commit timestamp. If we only fetch the latest commit, I think if will fail to find the timestamp for any files that was not part of that commit.
